export default {
  GET_USERS: 'GET_USERS',
  GET_USERS_ERROR: 'GET_USERS_ERROR',
  SET_URL_OBJECT: 'SET_URL_OBJECT',
  GET_POSITIONS: 'GET_POSITIONS',
  GET_TOKEN: 'GET_TOKEN',
  REFRESH_USERS: 'REFRESH_USERS',
  SPINNER_ON: 'SPINNER_ON',
  SPINNER_OFF: 'SPINNER_OFF',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_MOBILE_MENU: 'OPEN_MOBILE_MENU',
  CLOSE_MOBILE_MENU: 'CLOSE_MOBILE_MENU',
};
